export const MOCK_CATALOG_PRODUCTS = [
  {
    id: "m1",
    name: "Hộp Quà Lãng Mạn - Eternal Love Special Edition",
    slug: "hop-qua-lang-man-eternal-love",
    sku: "GIFT-EL-001",
    description: "Set quà tặng cao cấp gồm hoa sáp thơm, ly sứ khắc tên, thiệp viết tay và đèn LED trang trí lãng mạn.",
    basePrice: 590000,
    salePrice: 490000,
    stock: 50,
    isFeatured: true,
    isNew: true,
    isCustomizable: true,
    category: { id: "8bc6cdbb-b6cb-4b71-b0db-3cdb4b7c7b12", name: "Combo Quà Tặng", slug: "combo-qua-tang" },
    media: [{ url: "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=500&auto=format&fit=crop&q=80", isThumbnail: true }]
  },
  {
    id: "m2",
    name: "Sổ Tay Da Thật Khắc Tên Cá Nhân Hóa",
    slug: "so-tay-da-that-khac-ten",
    sku: "GIFT-NB-002",
    description: "Sổ bìa da bò thật cao cấp, giấy nhám kraft vintage, hỗ trợ khắc laze tên và lời chúc ý nghĩa theo yêu cầu.",
    basePrice: 350000,
    stock: 120,
    isFeatured: true,
    isNew: false,
    isCustomizable: true,
    category: { id: "a50c8b9d-472e-4b21-995a-6a56e0cfd17c", name: "Sổ Da & Bút", slug: "so-da-but" },
    media: [{ url: "https://images.unsplash.com/photo-1544816155-12df9643f363?w=500&auto=format&fit=crop&q=80", isThumbnail: true }]
  },
  {
    id: "m3",
    name: "Ly Sứ Cao Cấp Vẽ Tay - Men Hỏa Biến",
    slug: "ly-su-men-hoa-bien",
    sku: "GIFT-MUG-003",
    description: "Ly sứ Bát Tràng tráng men hỏa biến độc bản, chế tác tinh xảo, màu sắc biến đổi theo nhiệt độ lò.",
    basePrice: 220000,
    salePrice: 180000,
    stock: 200,
    isFeatured: false,
    isNew: true,
    isCustomizable: false,
    category: { id: "7bf807db-5e04-4cda-9218-e3cf4d8c071a", name: "Ly Sứ", slug: "ly-su" },
    media: [{ url: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=500&auto=format&fit=crop&q=80", isThumbnail: true }]
  },
  {
    id: "m4",
    name: "Set Quà Lưu Niệm Đồ Gỗ Bản Đồ Việt Nam",
    slug: "tranh-go-ban-do-viet-nam",
    sku: "GIFT-WOOD-004",
    description: "Tranh khắc gỗ 3D Bản đồ Việt Nam đầy đủ Hoàng Sa, Trường Sa, sử dụng chất liệu gỗ tự nhiên sơn dầu bảo vệ.",
    basePrice: 1200000,
    salePrice: 950000,
    stock: 15,
    isFeatured: true,
    isNew: true,
    isCustomizable: true,
    category: { id: "6cde07fb-b783-4a11-893f-d3c26cbdfa53", name: "Đồ Lưu Niệm", slug: "do-luu-niem" },
    media: [{ url: "https://images.unsplash.com/photo-1581783898377-1c85bf937427?w=500&auto=format&fit=crop&q=80", isThumbnail: true }]
  },
  {
    id: "m5",
    name: "Bút Ký Kim Loại Khắc Tên Mạ Vàng Lux",
    slug: "but-ky-kim-loai-khac-ten",
    sku: "GIFT-PEN-005",
    description: "Bút dạ bi kim loại mạ vàng sang trọng, nét mực trơn tru, đi kèm hộp nhung lót lụa cao cấp làm quà tặng doanh nghiệp.",
    basePrice: 290000,
    stock: 80,
    isFeatured: false,
    isNew: false,
    isCustomizable: true,
    category: { id: "a50c8b9d-472e-4b21-995a-6a56e0cfd17c", name: "Sổ Da & Bút", slug: "so-da-but" },
    media: [{ url: "https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=500&auto=format&fit=crop&q=80", isThumbnail: true }]
  },
  {
    id: "m6",
    name: "Cốc Giữ Nhiệt Laze Khắc Logo Hộp Sang Trọng",
    slug: "coc-giu-nhiet-khac-logo",
    sku: "GIFT-MUG-006",
    description: "Ly giữ nhiệt thép không gỉ 304 dung tích 500ml, giữ nóng lạnh 12 giờ, hỗ trợ thiết kế khắc laze tên hoặc logo doanh nghiệp.",
    basePrice: 280000,
    salePrice: 240000,
    stock: 150,
    isFeatured: false,
    isNew: true,
    isCustomizable: true,
    category: { id: "7bf807db-5e04-4cda-9218-e3cf4d8c071a", name: "Ly Sứ", slug: "ly-su" },
    media: [{ url: "https://images.unsplash.com/photo-1577937927133-66ef06acdf18?w=500&auto=format&fit=crop&q=80", isThumbnail: true }]
  },
  {
    id: "m7",
    name: "Set Hộp Trà Cao Cấp Gỗ Hương Tự Nhiên",
    slug: "set-hop-tra-go-huong",
    sku: "GIFT-TEA-007",
    description: "Hộp đựng trà chế tác thủ công từ gỗ hương đỏ nguyên khối, mùi thơm tự nhiên kết hợp cùng trà ô long thượng hạng.",
    basePrice: 750000,
    stock: 35,
    isFeatured: true,
    isNew: false,
    isCustomizable: false,
    category: { id: "6cde07fb-b783-4a11-893f-d3c26cbdfa53", name: "Đồ Lưu Niệm", slug: "do-luu-niem" },
    media: [{ url: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=500&auto=format&fit=crop&q=80", isThumbnail: true }]
  },
  {
    id: "m8",
    name: "Album Ảnh Gỗ Gấp Gọn Lưu Giữ Kỷ Niệm",
    slug: "album-anh-go-luu-niem",
    sku: "GIFT-ALB-008",
    description: "Album ảnh trang bìa gỗ ép cao cấp, ruột giấy mỹ thuật đen dày dặn, tặng kèm decal góc dán ảnh và bút nhũ viết lời chúc.",
    basePrice: 420000,
    salePrice: 380000,
    stock: 90,
    isFeatured: true,
    isNew: false,
    isCustomizable: true,
    category: { id: "6cde07fb-b783-4a11-893f-d3c26cbdfa53", name: "Đồ Lưu Niệm", slug: "do-luu-niem" },
    media: [{ url: "https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=500&auto=format&fit=crop&q=80", isThumbnail: true }]
  }
];

export const SORT_OPTIONS = [
  { name: 'Mới nhất', value: 'newest' },
  { name: 'Giá tăng dần', value: 'price-asc' },
  { name: 'Giá giảm dần', value: 'price-desc' },
  { name: 'Phổ biến/Bán chạy', value: 'sales' }
];
