spring.application.name=tthieu.haniu

# Database Connection (Supabase PostgreSQL / Local)
spring.datasource.url=${DATABASE_URL_POSTGRE:jdbc:postgresql://localhost:5432/haniu?schema=public&sslmode=disable}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:admin}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Properties
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server port configured via Render or fallback to 8000
server.port=${PORT:8000}

# Elasticsearch Configuration
spring.elasticsearch.uris=${ELASTICSEARCH_NODE:http://localhost:9200}

# Multipart File Upload Configurations
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
